spring:
    application:
        name: cart-service
    data:
        mongodb:
           uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${SPRING_DATA_MONGODB_HOST}:${SPRING_DATA_MONGODB_PORT}/${SPRING_DATA_MONGODB_DATABASE}?authSource=admin
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9060

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    instance:
        hostname: cart-service