apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-service
  template:
    metadata:
      labels:
        app: category-service
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            - sh
            - -c
            - "until nc -z -v -w30 purely-category-service 27017; do echo 'Waiting for MongoDB...'; sleep 5; done;"
        - name: wait-for-eureka
          image: busybox
          command:
            - sh
            - -c
            - "until nc -z -v -w30 eureka-server 8761; do echo 'Waiting for Eureka...'; sleep 5; done;"    
      
      containers:
        - name: category-service
          image: mohamedelrefy20/category-service:latest
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_SECURITY_LOG_LEVEL
              value: DEBUG
            - name: eureka.client.service-url.defaultZone
              value: http://eureka-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: category-service
spec:
  selector:
    app: category-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP