apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: purely-app
data:
  SPRING_APPLICATION_NAME: order-service
  SPRING_DATA_MONGODB_HOST: purely-order-service
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: purely_order_service
  SPRING_SECURITY_LOG_LEVEL: DEBUG
  eureka_client_service_url_defaultZone: http://eureka-server:8761/eureka/
